const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Function: 0},
	{LocalStorage: 0},
	{Sine: 0},
	{btn_back: 0},
	{btn_blueFixe: 0},
	{situation: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{btn_blueMove: 0},
	{btn_greenFixe: 0},
	{btn_greenMove: 0},
	{btn_MenuGO: 0},
	{btn_MenuWinner: 0},
	{btn_options: 0},
	{btn_redFixe: 0},
	{btn_yellowFixe: 0},
	{btn_yellowMove: 0},
	{btn_redMove: 0},
	{btnCredits: 0},
	{btnEasy: 0},
	{btnFoward: 0},
	{btnHard: 0},
	{btnInsta: 0},
	{btnMedium: 0},
	{btnRestart: 0},
	{btnRestartWinner: 0},
	{btnTwitter: 0},
	{playButton: 0},
	{btn_Special01: 0},
	{btn_Special02: 0},
	{btn_Special03: 0},
	{btn_Special04: 0},
	{arrowSelection: 0},
	{border_lifeBarAnim: 0},
	{border_lifeBarFixe: 0},
	{frameDifficulty: 0},
	{teste_MULIPLY_score: 0},
	{lifeBar: 0},
	{score_top_ui: 0},
	{bar_especial01: 0},
	{bar_especial02: 0},
	{border_specialBar: 0},
	{bestScoreLevelSelect01_new: 0},
	{bestScoreLevelSelect02_new: 0},
	{bestScoreLevelSelect03_new: 0},
	{score_game_label_new: 0},
	{winnerScoreLabel_new: 0},
	{bg: 0},
	{bg_credits: 0},
	{bg_gameOverOK: 0},
	{bg_levelselect: 0},
	{bg_options: 0},
	{bg_splash: 0},
	{bg_winnerOK: 0},
	{colision_button_overlap01: 0},
	{colision_button_overlap02: 0},
	{music1_colision: 0},
	{music2_colision: 0},
	{music3_colision: 0},
	{spawn01: 0},
	{spawn02: 0},
	{spawn03: 0},
	{spawn04: 0},
	{Fade: 0},
	{word_amazing: 0},
	{word_fantastic: 0},
	{word_awesome: 0},
	{word_good: 0},
	{word_professional: 0},
	{winner_you_rock: 0},
	{flameButtonBlue: 0},
	{flameButtonGreen: 0},
	{flameButtonRed: 0},
	{flameButtonYellow: 0},
	{fret_movement: 0},
	{flameButtonSpecial: 0},
	{eletric_buttons: 0},
	{eletric_frets: 0},
	{white_flashSpecial: 0},
	{guitarFrets: 0},
	{hand_youRock: 0},
	{x10: 0},
	{x200: 0},
	{x100: 0},
	{x25: 0},
	{x50: 0},
	{specialTimer: 0},
	{specialBar: 0},
	{special: 0},
	{multiplyScore: 0},
	{levelSelect: 0},
	{level1_timer: 0},
	{level2_timer: 0},
	{level3_timer: 0},
	{difficulty: 0},
	{score: 0},
	{record1: 0},
	{record2: 0},
	{record3: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_blueFixe: class extends self.ISpriteInstance {},
	btn_blueMove: class extends self.ISpriteInstance {},
	btn_greenFixe: class extends self.ISpriteInstance {},
	btn_greenMove: class extends self.ISpriteInstance {},
	btn_MenuGO: class extends self.ISpriteInstance {},
	btn_MenuWinner: class extends self.ISpriteInstance {},
	btn_options: class extends self.ISpriteInstance {},
	btn_redFixe: class extends self.ISpriteInstance {},
	btn_yellowFixe: class extends self.ISpriteInstance {},
	btn_yellowMove: class extends self.ISpriteInstance {},
	btn_redMove: class extends self.ISpriteInstance {},
	btnCredits: class extends self.ISpriteInstance {},
	btnEasy: class extends self.ISpriteInstance {},
	btnFoward: class extends self.ISpriteInstance {},
	btnHard: class extends self.ISpriteInstance {},
	btnInsta: class extends self.ISpriteInstance {},
	btnMedium: class extends self.ISpriteInstance {},
	btnRestart: class extends self.ISpriteInstance {},
	btnRestartWinner: class extends self.ISpriteInstance {},
	btnTwitter: class extends self.ISpriteInstance {},
	playButton: class extends self.ISpriteInstance {},
	btn_Special01: class extends self.ISpriteInstance {},
	btn_Special02: class extends self.ISpriteInstance {},
	btn_Special03: class extends self.ISpriteInstance {},
	btn_Special04: class extends self.ISpriteInstance {},
	arrowSelection: class extends self.ISpriteInstance {},
	border_lifeBarAnim: class extends self.ISpriteInstance {},
	border_lifeBarFixe: class extends self.ISpriteInstance {},
	frameDifficulty: class extends self.ISpriteInstance {},
	teste_MULIPLY_score: class extends self.ITextInstance {},
	lifeBar: class extends self.ISpriteInstance {},
	score_top_ui: class extends self.ISpriteInstance {},
	bar_especial01: class extends self.ITiledBackgroundInstance {},
	bar_especial02: class extends self.ITiledBackgroundInstance {},
	border_specialBar: class extends self.ISpriteInstance {},
	bestScoreLevelSelect01_new: class extends self.ISpriteFontInstance {},
	bestScoreLevelSelect02_new: class extends self.ISpriteFontInstance {},
	bestScoreLevelSelect03_new: class extends self.ISpriteFontInstance {},
	score_game_label_new: class extends self.ISpriteFontInstance {},
	winnerScoreLabel_new: class extends self.ISpriteFontInstance {},
	bg: class extends self.ISpriteInstance {},
	bg_credits: class extends self.ISpriteInstance {},
	bg_gameOverOK: class extends self.ISpriteInstance {},
	bg_levelselect: class extends self.ISpriteInstance {},
	bg_options: class extends self.ISpriteInstance {},
	bg_splash: class extends self.ISpriteInstance {},
	bg_winnerOK: class extends self.ISpriteInstance {},
	colision_button_overlap01: class extends self.ISpriteInstance {},
	colision_button_overlap02: class extends self.ISpriteInstance {},
	music1_colision: class extends self.ISpriteInstance {},
	music2_colision: class extends self.ISpriteInstance {},
	music3_colision: class extends self.ISpriteInstance {},
	spawn01: class extends self.ISpriteInstance {},
	spawn02: class extends self.ISpriteInstance {},
	spawn03: class extends self.ISpriteInstance {},
	spawn04: class extends self.ISpriteInstance {},
	word_amazing: class extends self.ISpriteInstance {},
	word_fantastic: class extends self.ISpriteInstance {},
	word_awesome: class extends self.ISpriteInstance {},
	word_good: class extends self.ISpriteInstance {},
	word_professional: class extends self.ISpriteInstance {},
	winner_you_rock: class extends self.ISpriteInstance {},
	flameButtonBlue: class extends self.ISpriteInstance {},
	flameButtonGreen: class extends self.ISpriteInstance {},
	flameButtonRed: class extends self.ISpriteInstance {},
	flameButtonYellow: class extends self.ISpriteInstance {},
	fret_movement: class extends self.ISpriteInstance {},
	flameButtonSpecial: class extends self.ISpriteInstance {},
	eletric_buttons: class extends self.ISpriteInstance {},
	eletric_frets: class extends self.ISpriteInstance {},
	white_flashSpecial: class extends self.ITiledBackgroundInstance {},
	guitarFrets: class extends self.ISpriteInstance {},
	hand_youRock: class extends self.ISpriteInstance {},
	x10: class extends self.ISpriteInstance {},
	x200: class extends self.ISpriteInstance {},
	x100: class extends self.ISpriteInstance {},
	x25: class extends self.ISpriteInstance {},
	x50: class extends self.ISpriteInstance {}
}